/**
 * A tiny stand-in for Immich 3.2.0 that serves the endpoints immich-bookbinder uses, with real
 * JPEGs generated by sharp. Used by the server tests and runnable on its own for local development
 * when no Immich is reachable:
 *
 *   corepack pnpm --filter @bookbinder/server exec tsx src/test/fake-immich.ts --port 2283 --photos 80
 *
 * Then in the app's Settings use http://127.0.0.1:2283 and any API key of 10+ characters.
 */
import Fastify, { type FastifyInstance } from 'fastify';
import sharp from 'sharp';

export interface FakeAsset {
  id: string;
  fileName: string;
  width: number;
  height: number;
  takenAt: string;
  city?: string;
  country?: string;
  description?: string;
  isFavorite: boolean;
  albumIds: string[];
  type?: 'IMAGE' | 'VIDEO';
  stackPrimaryId?: string;
  orientation?: string;
  hue: number;
}

export interface FakeImmichOptions {
  port?: number;
  host?: string;
  photos?: number;
  /** Long edge of the "original" files (default 1800 to keep tests quick). */
  originalLongEdge?: number;
  /** Require this API key (default: accept any key of 10+ characters). */
  apiKey?: string;
  logger?: boolean;
}

export interface FakeImmich {
  url: string;
  app: FastifyInstance;
  assets: FakeAsset[];
  albums: { id: string; name: string }[];
  /** Requests seen, oldest first. */
  requests: { method: string; path: string }[];
  close(): Promise<void>;
}

const SHAPES: Array<[number, number]> = [
  [3, 2],
  [2, 3],
  [1, 1],
  [4, 3],
  [16, 9],
  [3, 4],
  [3, 2],
  [3, 2],
];
const CITIES = ['Lisbon', 'Sintra', 'Porto', 'Pinhão'];

export function makeFakeAssets(n: number, longEdge = 1800): FakeAsset[] {
  const out: FakeAsset[] = [];
  for (let i = 0; i < n; i++) {
    const [rw, rh] = SHAPES[(i * 5) % SHAPES.length]!;
    const scale = longEdge / Math.max(rw, rh);
    const day = Math.floor(i / 12);
    const albumIds = ['album-trip'];
    if (i % 4 === 0) albumIds.push('album-best');
    out.push({
      id: `asset-${String(i).padStart(4, '0')}`,
      fileName: `IMG_${4000 + i}.JPG`,
      width: Math.round(rw * scale),
      height: Math.round(rh * scale),
      takenAt: new Date(Date.UTC(2026, 4, 12 + day, 8 + (i % 12), (i * 7) % 60)).toISOString(),
      city: CITIES[day % CITIES.length]!,
      country: 'Portugal',
      ...(i % 9 === 0 ? { description: `Photo ${i}: ${CITIES[day % CITIES.length]} at ${8 + (i % 12)}h` } : {}),
      isFavorite: i % 5 === 0,
      albumIds,
      hue: (i * 47) % 360,
    });
  }
  return out;
}

function hsl(h: number, s: number, l: number): string {
  return `hsl(${h} ${s}% ${l}%)`;
}

/** A recognisable test photo: gradient, big index label, and a tick mark at the focal corner. */
export async function renderFakeJpeg(a: FakeAsset, longEdge: number, quality = 82): Promise<Buffer> {
  const scale = longEdge / Math.max(a.width, a.height);
  const w = Math.max(16, Math.round(a.width * scale));
  const h = Math.max(16, Math.round(a.height * scale));
  const label = a.id.replace('asset-', '#');
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
  <defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${hsl(a.hue, 45, 78)}"/><stop offset="0.6" stop-color="${hsl(a.hue, 50, 48)}"/><stop offset="1" stop-color="${hsl(a.hue, 40, 22)}"/></linearGradient></defs>
  <rect width="100%" height="100%" fill="url(#g)"/>
  <circle cx="${w * 0.7}" cy="${h * 0.3}" r="${Math.min(w, h) * 0.08}" fill="rgba(255,240,210,0.85)"/>
  <path d="M0 ${h * 0.72} Q ${w * 0.25} ${h * 0.55} ${w * 0.5} ${h * 0.68} T ${w} ${h * 0.6} V ${h} H 0 Z" fill="rgba(10,20,25,0.45)"/>
  <text x="${w / 2}" y="${h / 2}" font-family="Arial, sans-serif" font-size="${Math.min(w, h) * 0.22}" font-weight="700" fill="rgba(255,255,255,0.92)" text-anchor="middle" dominant-baseline="middle">${label}</text>
  <text x="${w / 2}" y="${h / 2 + Math.min(w, h) * 0.16}" font-family="Arial, sans-serif" font-size="${Math.min(w, h) * 0.07}" fill="rgba(255,255,255,0.8)" text-anchor="middle">${a.width}×${a.height} · ${a.city ?? ''}</text>
</svg>`;
  return sharp(Buffer.from(svg)).jpeg({ quality }).toBuffer();
}

function assetDto(a: FakeAsset) {
  return {
    id: a.id,
    deviceAssetId: a.id,
    ownerId: 'user-1',
    deviceId: 'fake',
    libraryId: null,
    type: a.type ?? 'IMAGE',
    originalPath: `/photos/${a.fileName}`,
    originalFileName: a.fileName,
    originalMimeType: 'image/jpeg',
    thumbhash: null,
    fileCreatedAt: a.takenAt,
    fileModifiedAt: a.takenAt,
    localDateTime: a.takenAt,
    updatedAt: a.takenAt,
    createdAt: a.takenAt,
    isFavorite: a.isFavorite,
    isArchived: false,
    isTrashed: false,
    isOffline: false,
    isEdited: false,
    visibility: 'timeline',
    duration: null,
    hasMetadata: true,
    checksum: 'AAAA',
    width: a.width,
    height: a.height,
    exifInfo: {
      make: 'Fake',
      model: 'Camera',
      exifImageWidth: a.orientation && Number(a.orientation) >= 5 ? a.height : a.width,
      exifImageHeight: a.orientation && Number(a.orientation) >= 5 ? a.width : a.height,
      fileSizeInByte: 1000,
      orientation: a.orientation ?? '1',
      dateTimeOriginal: a.takenAt,
      modifyDate: a.takenAt,
      timeZone: 'UTC',
      lensModel: null,
      fNumber: 2.8,
      focalLength: 35,
      iso: 100,
      exposureTime: '1/250',
      latitude: null,
      longitude: null,
      city: a.city ?? null,
      state: null,
      country: a.country ?? null,
      description: a.description ?? '',
      projectionType: null,
      rating: null,
    },
    people: [],
    tags: [],
    duplicateId: null,
    stack: a.stackPrimaryId ? { id: `stack-${a.stackPrimaryId}`, primaryAssetId: a.stackPrimaryId, assetCount: 2 } : null,
    resized: true,
  };
}

export async function startFakeImmich(opts: FakeImmichOptions = {}): Promise<FakeImmich> {
  const longEdge = opts.originalLongEdge ?? 1800;
  const assets = makeFakeAssets(opts.photos ?? 40, longEdge);
  const albums = [
    { id: 'album-trip', name: 'Portugal 2026' },
    { id: 'album-best', name: 'Best of Portugal' },
    { id: 'album-empty', name: 'Empty album' },
  ];
  const requests: { method: string; path: string }[] = [];
  const app = Fastify({ logger: opts.logger ?? false });
  const byId = new Map(assets.map((a) => [a.id, a]));
  const imageCache = new Map<string, Promise<Buffer>>();
  const image = (a: FakeAsset, edge: number): Promise<Buffer> => {
    const key = `${a.id}:${edge}`;
    let p = imageCache.get(key);
    if (!p) {
      p = renderFakeJpeg(a, edge);
      imageCache.set(key, p);
    }
    return p;
  };

  app.addHook('onRequest', async (req, reply) => {
    requests.push({ method: req.method, path: req.url.split('?')[0]! });
    if (req.url.startsWith('/api/server/version')) return;
    const key = req.headers['x-api-key'];
    const ok = typeof key === 'string' && (opts.apiKey ? key === opts.apiKey : key.length >= 10);
    if (!ok) return reply.code(401).send({ message: 'Invalid API key', statusCode: 401 });
  });

  const albumDto = (al: { id: string; name: string }) => {
    const members = assets.filter((a) => a.albumIds.includes(al.id));
    const dates = members.map((m) => m.takenAt).sort();
    return {
      id: al.id,
      albumName: al.name,
      description: '',
      albumThumbnailAssetId: members[0]?.id ?? null,
      albumUsers: [],
      assetCount: members.length,
      createdAt: '2026-05-22T10:00:00.000Z',
      updatedAt: '2026-05-22T10:00:00.000Z',
      hasSharedLink: false,
      isActivityEnabled: false,
      ownerId: 'user-1',
      owner: { id: 'user-1', name: 'Kevin', email: 'kevin@example.com', profileImagePath: '', avatarColor: 'primary', profileChangedAt: '2026-01-01T00:00:00.000Z' },
      shared: false,
      ...(dates.length ? { startDate: dates[0], endDate: dates[dates.length - 1] } : {}),
    };
  };

  app.get('/api/server/version', async () => ({ major: 3, minor: 2, patch: 0, prerelease: null }));
  app.get('/api/server/about', async () => ({ version: 'v3.2.0', versionUrl: 'https://example.com', licensed: false }));
  app.get('/api/users/me', async () => ({ id: 'user-1', name: 'Kevin', email: 'kevin@example.com' }));
  app.get('/api/assets/statistics', async () => ({ images: assets.length, videos: 0, total: assets.length }));
  app.get('/api/albums', async () => albums.map(albumDto));
  app.get<{ Params: { id: string } }>('/api/albums/:id', async (req, reply) => {
    const al = albums.find((x) => x.id === req.params.id);
    if (!al) return reply.code(400).send({ message: 'Not found or no album.read access', statusCode: 400 });
    return albumDto(al);
  });
  app.get('/api/people', async () => ({ people: [], total: 0, hidden: 0, hasNextPage: false }));
  // Metadata search with the 3.2 cursor paging; pages are capped at 10 so callers must follow nextCursor.
  app.post<{ Body: { isFavorite?: boolean; albumIds?: string[]; size?: number; cursor?: string; type?: string } }>('/api/search/metadata', async (req) => {
    const body = req.body ?? {};
    const matching = assets.filter(
      (a) =>
        (body.isFavorite === undefined || a.isFavorite === body.isFavorite) &&
        (body.albumIds === undefined || a.albumIds.some((id) => body.albumIds!.includes(id))) &&
        (body.type === undefined || (a.type ?? 'IMAGE') === body.type),
    );
    const pageSize = Math.min(body.size ?? 250, 10);
    const start = body.cursor ? Number(body.cursor) : 0;
    const items = matching.slice(start, start + pageSize);
    const next = start + pageSize < matching.length ? String(start + pageSize) : null;
    return {
      albums: { total: 0, count: 0, items: [], facets: [] },
      assets: { total: matching.length, count: items.length, items: items.map(assetDto), facets: [], nextCursor: next, nextPage: null },
    };
  });
  app.get<{ Params: { id: string }; Querystring: { size?: string } }>('/api/assets/:id/thumbnail', async (req, reply) => {
    const a = byId.get(req.params.id);
    if (!a) return reply.code(404).send({ message: 'Not found', statusCode: 404 });
    const size = req.query.size ?? 'thumbnail';
    const edge = size === 'thumbnail' ? 250 : size === 'preview' ? 1440 : longEdge;
    return reply.type('image/jpeg').send(await image(a, Math.min(edge, longEdge)));
  });
  app.get<{ Params: { id: string } }>('/api/assets/:id/original', async (req, reply) => {
    const a = byId.get(req.params.id);
    if (!a) return reply.code(404).send({ message: 'Not found', statusCode: 404 });
    return reply.type('image/jpeg').send(await image(a, longEdge));
  });
  app.get('/api/faces', async () => []);
  app.get('/api/duplicates', async () => []);
  app.get('/api/tags', async () => []);
  app.get('/api/timeline/buckets', async () => []);
  app.get('/api/map/markers', async () => []);

  const url = await app.listen({ port: opts.port ?? 0, host: opts.host ?? '127.0.0.1' });
  return { url, app, assets, albums, requests, close: () => app.close() };
}

// Run directly: node/tsx src/test/fake-immich.ts [--port N] [--photos N]
if (process.argv[1] && /fake-immich\.[tj]s$/.test(process.argv[1])) {
  const arg = (name: string, fallback: number): number => {
    const i = process.argv.indexOf(`--${name}`);
    return i > 0 ? Number(process.argv[i + 1]) : fallback;
  };
  startFakeImmich({ port: arg('port', 2283), photos: arg('photos', 80), originalLongEdge: arg('edge', 2400), logger: true })
    .then((s) => console.log(`fake Immich listening at ${s.url} with ${s.assets.length} photos in ${s.albums.length} albums`))
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
