import type { LuluEnv, ShippingAddress, ShippingLevel } from '@bookbinder/shared';
import createClient from 'openapi-fetch';
import { z } from 'zod';
import type { paths } from './generated/lulu.js';

/*
 * Typed wrapper over the Lulu Print API (specs/lulu-openapi.yml, generated into ./generated by
 * `pnpm generate:lulu`). OAuth2 client credentials with a cached token; every response the app
 * relies on is narrowed with a zod schema because Lulu's spec leaves most fields optional and the
 * status endpoint returns `line_item_statuses` that the schema does not even list.
 */

export const LULU_BASE_URLS: Record<LuluEnv, string> = {
  sandbox: 'https://api.sandbox.lulu.com',
  production: 'https://api.lulu.com',
};

export const TOKEN_PATH = '/auth/realms/glasstree/protocol/openid-connect/token';

/** Refresh the cached token this long before Lulu says it expires. */
const TOKEN_SAFETY_MS = 60_000;

export class LuluApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly path: string,
    public readonly body?: unknown,
  ) {
    super(`Lulu ${path} failed with HTTP ${status}${describeLuluBody(body)}`);
    this.name = 'LuluApiError';
  }
}

/** Flattens Lulu's error bodies: `{detail}`, OAuth `{error, error_description}`, or DRF field maps. */
export function describeLuluBody(body: unknown): string {
  const lines = luluErrorLines(body);
  return lines.length > 0 ? `: ${lines.join('; ')}` : '';
}

export function luluErrorLines(body: unknown, prefix = ''): string[] {
  if (body === null || body === undefined) return [];
  if (typeof body === 'string') return body.trim() ? [prefix ? `${prefix}: ${body.trim()}` : body.trim()] : [];
  if (Array.isArray(body)) return body.flatMap((b) => luluErrorLines(b, prefix));
  if (typeof body === 'object') {
    const o = body as Record<string, unknown>;
    if (typeof o.error_description === 'string') return [o.error_description];
    if (typeof o.detail === 'string') return [o.detail];
    if (typeof o.message === 'string') return [o.message];
    return Object.entries(o).flatMap(([k, v]) => luluErrorLines(v, prefix ? `${prefix}.${k}` : k)).slice(0, 12);
  }
  return [];
}

/* ---------- Response schemas (only what the app reads) ---------- */

const Decimal = z.union([z.string(), z.number()]).transform((v) => String(v));

export const LuluToken = z.object({ access_token: z.string().min(1), expires_in: z.number().optional() });

export const LuluCoverDimensions = z.object({ width: Decimal, height: Decimal, unit: z.enum(['pt', 'mm', 'inch']).default('pt') });
export type LuluCoverDimensions = z.infer<typeof LuluCoverDimensions>;

export const LuluFileValidation = z.object({
  id: z.number().int(),
  /**
   * Interior: VALIDATING/VALIDATED/ERROR; cover: NORMALIZING/NORMALIZED/ERROR (plus a few in-between names).
   * The sandbox answers the create call (201) with `null` before validation has started: treat as pending.
   */
  status: z.string().nullish(),
  errors: z.array(z.string()).nullish(),
  page_count: z.union([z.string(), z.number()]).nullish(),
});
export type LuluFileValidation = z.infer<typeof LuluFileValidation>;

export const LuluShippingOptionRow = z.object({
  level: z.string(),
  cost_excl_tax: z.string().nullish(),
  currency: z.string().nullish(),
  traceable: z.boolean().optional(),
  min_delivery_date: z.string().nullish(),
  max_delivery_date: z.string().nullish(),
  total_days_min: z.number().nullish(),
  total_days_max: z.number().nullish(),
});
export const LuluShippingOptions = z.array(LuluShippingOptionRow);

const CostBlock = z.object({ total_cost_excl_tax: Decimal.optional(), total_cost_incl_tax: Decimal.optional(), total_tax: Decimal.optional() });
export const LuluCostCalculation = z.object({
  currency: z.string(),
  line_item_costs: z.array(
    z.object({
      quantity: z.number(),
      cost_excl_discounts: Decimal.optional(),
      unit_tier_cost: Decimal.nullish(),
      total_cost_excl_tax: Decimal,
      total_cost_incl_tax: Decimal,
      total_tax: Decimal.optional(),
      discounts: z.array(z.object({ amount: Decimal, description: z.string() })).nullish(),
    }),
  ),
  shipping_cost: CostBlock.nullish(),
  fulfillment_cost: CostBlock.nullish(),
  fees: z.array(z.object({ fee_type: z.string().optional(), total_cost_excl_tax: Decimal.optional(), total_cost_incl_tax: Decimal.optional() })).nullish(),
  total_cost_excl_tax: Decimal,
  total_cost_incl_tax: Decimal,
  total_tax: Decimal.optional(),
  total_discount_amount: Decimal.nullish(),
});
export type LuluCostCalculation = z.infer<typeof LuluCostCalculation>;

const LineItemMessages = z
  .object({
    error: z.string().nullish(),
    info: z.string().nullish(),
    tracking_id: z.string().nullish(),
    tracking_urls: z.array(z.string()).nullish(),
    carrier_name: z.string().nullish(),
    url: z.union([z.string(), z.array(z.string())]).nullish(),
    printable_normalization: z.object({ cover: z.array(z.string()).nullish(), interior: z.array(z.string()).nullish() }).nullish(),
  })
  .loose();

/**
 * Print-job status. The detail, list and webhook payloads carry `{ name, message, changed }`, but the
 * spec's own schema for `POST /print-jobs/` answers with the bare status name as a string (observed
 * against the sandbox as "unexpected response shape: status" on the 201). Both are narrowed to the object.
 */
const LuluJobStatusObject = z.object({ name: z.string(), message: z.string().nullish(), messages: LineItemMessages.nullish() });
export const LuluJobStatus = z.preprocess(
  (v) => (typeof v === 'string' ? { name: v } : v === null ? undefined : v),
  LuluJobStatusObject.optional(),
);

export const LuluPrintJob = z.object({
  id: z.number().int(),
  external_id: z.string().nullish(),
  status: LuluJobStatus,
  contact_email: z.string().nullish(),
  shipping_level: z.string().nullish(),
  date_created: z.string().nullish(),
  shipping_address: z
    .object({
      name: z.string().nullish(),
      street1: z.string().nullish(),
      street2: z.string().nullish(),
      city: z.string().nullish(),
      state_code: z.string().nullish(),
      postcode: z.string().nullish(),
      country_code: z.string().nullish(),
      phone_number: z.string().nullish(),
      email: z.string().nullish(),
    })
    .loose()
    .nullish(),
  line_items: z
    .array(
      z.object({
        id: z.number().int().optional(),
        title: z.string().nullish(),
        quantity: z.number().nullish(),
        external_id: z.string().nullish(),
        pod_package_id: z.string().nullish(),
        /** Read-only interior page count, on the line item itself in Lulu's schema. */
        page_count: z.number().nullish(),
        printable_normalization: z.object({ pod_package_id: z.string().nullish(), interior: z.object({ page_count: z.number().nullish() }).loose().nullish() }).loose().nullish(),
        status: z.object({ name: z.string(), messages: LineItemMessages.nullish() }).optional(),
        tracking_id: z.string().nullish(),
        tracking_urls: z.array(z.string()).nullish(),
      }),
    )
    .default([]),
});
export type LuluPrintJob = z.infer<typeof LuluPrintJob>;

export const LuluWebhook = z.object({ id: z.string(), is_active: z.boolean().default(true), topics: z.array(z.string()).default([]), url: z.string() });
export type LuluWebhook = z.infer<typeof LuluWebhook>;
const LuluWebhookList = z.union([z.array(LuluWebhook), z.object({ results: z.array(LuluWebhook) }).transform((v) => v.results)]);

export const LuluPrintJobStatus = z.object({
  name: z.string(),
  message: z.string().nullish(),
  changed: z.string().optional(),
  line_item_statuses: z.array(z.object({ name: z.string().optional(), messages: LineItemMessages.nullish(), line_item_id: z.number().optional() })).nullish(),
});
export type LuluPrintJobStatus = z.infer<typeof LuluPrintJobStatus>;

export const LuluPrintJobList = z.object({ count: z.number().int().optional(), results: z.array(z.unknown()).optional() });

/* ---------- Client ---------- */

export interface LuluClientOptions {
  env: LuluEnv;
  clientKey: string;
  clientSecret: string;
  /** Development only: a fake Lulu (LULU_BASE_URL); defaults to the environment's real base. */
  baseUrl?: string | undefined;
  fetch?: typeof globalThis.fetch;
  timeoutMs?: number;
}

/** A further book in a quote (M7 multiple line items). */
export interface QuoteLineItem {
  podPackageId: string;
  pageCount: number;
  quantity: number;
}

export interface PrintJobLineItem {
  title: string;
  quantity: number;
  podPackageId: string;
  interior: { sourceUrl: string; md5: string };
  cover: { sourceUrl: string; md5: string };
  externalId?: string;
}

export interface CreatePrintJobInput {
  contactEmail: string;
  externalId: string;
  shippingLevel: ShippingLevel;
  shippingAddress: ShippingAddress;
  lineItems: PrintJobLineItem[];
}

export type LuluClient = ReturnType<typeof createLuluClient>;

type CreateBody = NonNullable<paths['/print-jobs/']['post']['requestBody']>['content']['application/json'];

export function createLuluClient(opts: LuluClientOptions) {
  const baseUrl = (opts.baseUrl ?? LULU_BASE_URLS[opts.env]).replace(/\/+$/, '');
  const timeoutMs = opts.timeoutMs ?? 30_000;
  const fetchImpl: typeof globalThis.fetch = (input, init) =>
    (opts.fetch ?? globalThis.fetch)(input, { ...init, signal: init?.signal ?? AbortSignal.timeout(timeoutMs) });

  const api = createClient<paths>({ baseUrl, headers: { accept: 'application/json' }, fetch: (request) => fetchImpl(request) });

  let token: { value: string; expiresAt: number } | undefined;
  /** One token exchange at a time: parallel first calls share it instead of each asking Keycloak. */
  let tokenPromise: Promise<{ value: string; expiresAt: number }> | undefined;

  async function fetchToken(): Promise<{ value: string; expiresAt: number }> {
    const basic = Buffer.from(`${opts.clientKey}:${opts.clientSecret}`, 'utf8').toString('base64');
    const res = await fetchImpl(`${baseUrl}${TOKEN_PATH}`, {
      method: 'POST',
      headers: { authorization: `Basic ${basic}`, 'content-type': 'application/x-www-form-urlencoded', accept: 'application/json' },
      body: 'grant_type=client_credentials',
    });
    const body: unknown = await res.json().catch(() => undefined);
    if (!res.ok) throw new LuluApiError(res.status, TOKEN_PATH, body);
    const parsed = LuluToken.safeParse(body);
    if (!parsed.success) throw new LuluApiError(res.status, TOKEN_PATH, 'token response had no access_token');
    const ttl = (parsed.data.expires_in ?? 3600) * 1000;
    return { value: parsed.data.access_token, expiresAt: Date.now() + ttl };
  }

  async function bearer(force = false): Promise<string> {
    if (force || !token || Date.now() >= token.expiresAt - TOKEN_SAFETY_MS) {
      if (!tokenPromise) {
        tokenPromise = fetchToken().finally(() => {
          tokenPromise = undefined;
        });
      }
      token = await tokenPromise;
    }
    return `Bearer ${token.value}`;
  }

  /** Runs an authenticated call; a 401 invalidates the cached token and retries once. */
  async function authed<T>(path: string, schema: z.ZodType<T>, run: (headers: Record<string, string>) => Promise<{ data?: unknown; error?: unknown; response: Response }>): Promise<T> {
    let result = await run({ authorization: await bearer() });
    if (result.response.status === 401) {
      token = undefined;
      result = await run({ authorization: await bearer(true) });
    }
    if (!result.response.ok) throw new LuluApiError(result.response.status, path, result.error ?? result.data);
    const parsed = schema.safeParse(result.data);
    if (!parsed.success) {
      const issues = parsed.error.issues.map((i) => `${i.path.join('.') || '<root>'} (${i.message})`).join(', ');
      throw new LuluApiError(result.response.status, path, `unexpected response shape: ${issues}`);
    }
    return parsed.data;
  }

  return {
    baseUrl,
    env: opts.env,

    /** Proves the credentials: token exchange plus one authenticated call. */
    async listPrintJobs(query: { page_size?: number } = {}) {
      return authed('/print-jobs/', LuluPrintJobList, (headers) => api.GET('/print-jobs/', { params: { query }, headers }));
    },

    /** The account's print jobs, newest first, parsed one by one (rows the schema cannot read are skipped). */
    async listPrintJobsParsed(query: { page_size?: number } = { page_size: 50 }): Promise<LuluPrintJob[]> {
      const list = await this.listPrintJobs(query);
      return (list.results ?? []).map((r) => LuluPrintJob.safeParse(r)).filter((p) => p.success).map((p) => p.data);
    },

    /* ---------- Webhooks (M7) ---------- */

    async listWebhooks(): Promise<LuluWebhook[]> {
      return authed('/webhooks/', LuluWebhookList, (headers) => api.GET('/webhooks/', { headers }));
    },

    async subscribeWebhook(url: string): Promise<LuluWebhook> {
      return authed('/webhooks/', LuluWebhook, (headers) => api.POST('/webhooks/', { body: { topics: ['PRINT_JOB_STATUS_CHANGED'], url }, headers }));
    },

    async deleteWebhook(id: string): Promise<void> {
      await authed(`/webhooks/${id}/`, z.unknown(), (headers) => api.DELETE('/webhooks/{id}/', { params: { path: { id } }, headers }));
    },

    /** Asks Lulu to POST a dummy PRINT_JOB_STATUS_CHANGED payload to the webhook. */
    async testWebhook(id: string): Promise<void> {
      await authed(`/webhooks/${id}/test-submission/PRINT_JOB_STATUS_CHANGED/`, z.unknown(), (headers) =>
        api.POST('/webhooks/{id}/test-submission/{topic}/', { params: { path: { id, topic: 'PRINT_JOB_STATUS_CHANGED' } }, headers }),
      );
    },

    async coverDimensions(input: { podPackageId: string; pageCount: number; unit?: 'pt' | 'mm' | 'inch' }) {
      return authed('/cover-dimensions/', LuluCoverDimensions, (headers) =>
        api.POST('/cover-dimensions/', { body: { pod_package_id: input.podPackageId, interior_page_count: input.pageCount, unit: input.unit ?? 'pt' }, headers }),
      );
    },

    async validateInterior(input: { sourceUrl: string; podPackageId: string }) {
      return authed('/validate-interior/', LuluFileValidation, (headers) =>
        api.POST('/validate-interior/', { body: { source_url: input.sourceUrl, pod_package_id: input.podPackageId }, headers }),
      );
    },

    async getInteriorValidation(id: number) {
      return authed(`/validate-interior/${id}/`, LuluFileValidation, (headers) => api.GET('/validate-interior/{id}/', { params: { path: { id } }, headers }));
    },

    async validateCover(input: { sourceUrl: string; podPackageId: string; pageCount: number }) {
      return authed('/validate-cover/', LuluFileValidation, (headers) =>
        api.POST('/validate-cover/', { body: { source_url: input.sourceUrl, pod_package_id: input.podPackageId, interior_page_count: input.pageCount }, headers }),
      );
    },

    async getCoverValidation(id: number) {
      return authed(`/validate-cover/${id}/`, LuluFileValidation, (headers) => api.GET('/validate-cover/{id}/', { params: { path: { id } }, headers }));
    },

    async shippingOptions(input: { podPackageId: string; pageCount: number; quantity: number; address: ShippingAddress; currency?: string; extra?: readonly QuoteLineItem[] }) {
      const a = input.address;
      return authed('/shipping-options/', LuluShippingOptions, (headers) =>
        api.POST('/shipping-options/', {
          body: {
            ...(input.currency ? { currency: input.currency } : {}),
            line_items: [{ page_count: input.pageCount, pod_package_id: input.podPackageId, quantity: input.quantity }, ...(input.extra ?? []).map((li) => ({ page_count: li.pageCount, pod_package_id: li.podPackageId, quantity: li.quantity }))],
            shipping_address: {
              country: a.country_code,
              city: a.city,
              postcode: a.postcode,
              street1: a.street1,
              ...(a.street2 ? { street2: a.street2 } : {}),
              // The schema names the field `state`; Lulu's own example sends `state_code`. Both, so US/CA/AU quotes get the state either way.
              ...(a.state_code ? { state: a.state_code, state_code: a.state_code } : {}),
              phone_number: a.phone_number,
              name: a.name,
            },
          },
          headers,
        }),
      );
    },

    async costCalculation(input: { podPackageId: string; pageCount: number; quantity: number; address: ShippingAddress; shippingLevel: ShippingLevel; extra?: readonly QuoteLineItem[] }) {
      return authed('/print-job-cost-calculations/', LuluCostCalculation, (headers) =>
        api.POST('/print-job-cost-calculations/', {
          body: {
            line_items: [{ page_count: input.pageCount, pod_package_id: input.podPackageId, quantity: input.quantity }, ...(input.extra ?? []).map((li) => ({ page_count: li.pageCount, pod_package_id: li.podPackageId, quantity: li.quantity }))],
            shipping_address: toLuluAddress(input.address),
            shipping_option: input.shippingLevel,
          },
          headers,
        }),
      );
    },

    async createPrintJob(input: CreatePrintJobInput) {
      // The generated type marks the read-only `id` as required; the cast keeps the rest checked.
      const body = {
        contact_email: input.contactEmail,
        external_id: input.externalId,
        shipping_level: input.shippingLevel,
        shipping_address: toLuluAddress(input.shippingAddress),
        line_items: input.lineItems.map((li) => ({
          title: li.title,
          quantity: li.quantity,
          ...(li.externalId ? { external_id: li.externalId } : {}),
          printable_normalization: {
            pod_package_id: li.podPackageId,
            interior: { source_url: li.interior.sourceUrl, source_md5_sum: li.interior.md5 },
            cover: { source_url: li.cover.sourceUrl, source_md5_sum: li.cover.md5 },
          },
        })),
      } as unknown as CreateBody;
      return authed('/print-jobs/', LuluPrintJob, (headers) => api.POST('/print-jobs/', { body, headers }));
    },

    async getPrintJob(id: string) {
      return authed(`/print-jobs/${id}/`, LuluPrintJob, (headers) => api.GET('/print-jobs/{id}/', { params: { path: { id } }, headers }));
    },

    async getPrintJobStatus(id: string) {
      return authed(`/print-jobs/${id}/status/`, LuluPrintJobStatus, (headers) => api.GET('/print-jobs/{id}/status/', { params: { path: { id } }, headers }));
    },

    /** Lulu cancels a job through its status resource; allowed while CREATED/UNPAID. */
    async cancelPrintJob(id: string) {
      return authed(`/print-jobs/${id}/status/`, LuluPrintJobStatus, (headers) =>
        api.PUT('/print-jobs/{id}/status/', { params: { path: { id } }, body: { name: 'CANCELED' }, headers }),
      );
    },
  };
}

/** Lulu's `shipping_address` for cost calculations and print jobs (the shared schema already uses its names). */
function toLuluAddress(a: ShippingAddress) {
  return {
    name: a.name,
    street1: a.street1,
    ...(a.street2 ? { street2: a.street2 } : {}),
    city: a.city,
    ...(a.state_code ? { state_code: a.state_code } : {}),
    postcode: a.postcode,
    country_code: a.country_code,
    phone_number: a.phone_number,
    email: a.email,
  };
}
